name: Bytes
author: Sabersamus
softdepend: [ByteCraft]
main: com.github.Sabersamus.Bytes.Bytes
version: 1.0
commands:
    bytes:
        description: interact with your wallet
        usage: |
            /<command> tell
            /<command> balance
            /<command> give [player] [amount]
            /<command> donate [player] [amount]
        aliases: wallet